apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drupal-app-secrets
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: "Helm"
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    data:
      DB_HOST: {{ .Values.database.host | b64enc | quote }}
      DB_NAME: {{ .Values.database.name | b64enc | quote }}
      DB_USER: {{ .Values.database.user | b64enc | quote }}
      DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
