name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t andrewfreak/project:${{ github.sha }} -f app/Dockerfile .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u andrewfreak --password-stdin
          docker push andrewfreak/project:${{ github.sha }}
      - name: Update Helm Chart
        run: |
          sed -i "s/tag:.*/tag: ${{ github.sha }}/" helm/drupal-app/values.yaml
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update image tag to ${{ github.sha}}" || echo "No changes"
          git push
